#!/bin/sh
# Copyright 1995-2025 Richard M. Troth, all rights reserved. <plaintext>
#
#         Name: rls (shell script)
#               'ls' files in the user's UFT "receive pool"
#       Author: Rick Troth, Houston, Texas, USA
#         Date: 1995-Jan-14, Apr-29
#
#         Note: A per-UFT-file ".lf" file is created by the server.
#               This script uses the ".lf" files to provide listing.
#
#    Variables: Z - basename of this script for reporting
#               U - username of the person running this script
#               D - UFT spool directory for this user       UFT_SPOOLDIR
#

#
# get basename of this script for reporting
Z=`basename "$0"`

#
# some environments have a non-POSIX side:
case `uname -s` in
    VM/ESA|z/VM) # this section depends on the CMS implementation
        cms " pipe rls | > /tmp/$$.rls "
        cat /tmp/$$.rls ; RC="$?"
        rm -f /tmp/$$.rls
        exit $RC
        ;;
    OS/390)
        echo "$Z: operation not supported on MVS" 1>&2
        exit 28
        ;;
esac

#
# get username to know which UFT spool space sub-directory to use
U=`id | awk -F\( '{print $2}' | awk -F\) '{print $1}'`
if [ -z "$U" ] ; then U=$USER ; fi
if [ -z "$U" ] ; then U=$USERNAME ; fi

#
# here's hoping that per-user sub-dir does in fact exist
D=/usr/spool/uft/$U
if [ -n "$UFT_SPOOLDIR" ]; then D="$UFT_SPOOLDIR"; fi
mkdir -m 0700 "$D" 2> /dev/null
if [ ! -d "$D" ] ; then D=/usr/spool/uft/$U ; fi
mkdir -m 0700 "$D" 2> /dev/null
if [ ! -d "$D" ] ; then D=/var/spool/uft/$U ; fi
mkdir -m 0700 "$D" 2> /dev/null
if [ ! -d "$D" ] ; then
    echo "$Z: UFT configuration problem: no spool directory" 1>&2
    exec ls -ld "$D" ; fi        # 'ls' here throws an informative error
UFT_SPOOLDIR="$D"

#
# a simple command:
exec cat "$D"/*.lf

#exit


