#!/bin/sh
# Copyright 2025 Richard M. Troth, all rights reserved. <plaintext>
#
#         Name: rrm (shell script)
#               remove (purge) a file sent via UFT
#         Date: 2024-10-29 (Wed)
#       Author: Rick Troth, Cedarville, Ohio, USA
#
#         Note: this is a *really* simplistic script
#               The layout of the UFT spooling directories along with
#               the format of each ".cf" control file is intended to
#               simplify scripting, should you choose to do your own.
#
#    Variables: Z - basename of this script for reporting
#               U - username of the person running this script
#               D - UFT spool directory for this user       UFT_SPOOLDIR
#               S - spool file of interest
#

#
# get basename of this script for reporting
Z=`basename "$0"`

#
# some environments have a non-POSIX side:
case `uname -s` in
    VM/ESA|z/VM) # this section depends on the z/VM implementation
        echo "+ #cp purge * rdr $1"
        cms "cp purge * rdr $1"
        exit $?
        ;;
    OS/390)
        echo "$Z: operation not supported on MVS" 1>&2
        exit 28
        ;;
esac

#
# get username to know which UFT spool space sub-directory to use
U=`id | awk -F\( '{print $2}' | awk -F\) '{print $1}'`
if [ -z "$U" ] ; then U=$USER ; fi
if [ -z "$U" ] ; then U=$USERNAME ; fi

#
# here's hoping that per-user sub-dir does in fact exist
D=/usr/spool/uft/$U
if [ -n "$UFT_SPOOLDIR" ]; then D="$UFT_SPOOLDIR"; fi
mkdir -m 0700 "$D" 2> /dev/null
if [ ! -d "$D" ] ; then D=/usr/spool/uft/$U ; fi
mkdir -m 0700 "$D" 2> /dev/null
if [ ! -d "$D" ] ; then D=/var/spool/uft/$U ; fi
mkdir -m 0700 "$D" 2> /dev/null
if [ ! -d "$D" ] ; then
    echo "$Z: UFT configuration problem: no spool directory" 1>&2
    exec ls -ld "$D" ; fi        # 'ls' here throws an informative error
UFT_SPOOLDIR="$D"

#
# clean-up the spool ID .. four digits for historical reasons
S="$1"
if [ -z "$S" ] ; then S=1 ; fi
S=`echo "0000$S" | awk '{print substr($0,length($0)-3,4)}'`

#
# got this far? then discard the spool file (all components)
yes | rm $D/$S.*

exit

# some example UFT file attributes:
UFT_REMOTE=''                           # the sending user@host if available
UFT_SIZE='36K'                          # estimated size reported by sender
UFT_FROM='ltroth3'                      # sending user per the FILE command
UFT_USER='rmt'                          # intended recipient
UFT_TYPE='I'                            # text? binary? or something else?
UFT_NAME='uftcreqs.tar'                 # the name of the file, if available
UFT_DATE='2024-04-19 20:22:31'          # date stamp on the file being sent
UFT_RECFM='F'                           # record format, if applicable
UFT_LRECL='512'                         # record length, if applicable


